title: Sidans sida
author: TobiasP
email: mailamig@mail.mail
description: > # this means to ignore newlines until "baseurl:"
 P책 den h채r sidan kommer sp채nnande saker h채nda..

# social links
twitter_username: wingerlito # DO NOT include the @ character, or else the build will fail!
github_username:  TobiasPersson10 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
