title: Min sida
author: Tobias
email: minmail@mail.se
description: > # this means to ignore newlines until "baseurl:"
 Här kommer spännande saker att ske snart..
# social links
twitter_username: Wingerlito # DO NOT include the @ character, or else the build will fail!
github_username:  TobiasPersson10 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
